### ISSUE TITLE
Number of unique production builds deployed

### ISSUE THREAD

**Issue by henninghaakonsen** [nais/naiserator#52] opened 2019-03-08 08:58 UTC
With continuous delivery we push out smaller features to production to give users the newest features and fast fault handling. In many cases it would be interesting to see how many production builds were released since this gives a quick overview of the speed of the team.

I believe naiserator could push a metric which accumulates per new production build which is successfully deployed. It should be able to get the metric from grafana. It would be great if the metric was dated(like a counter which is scraped of a nais app) so that the team can follow the progression of builds to production.

**Comment by audunstrand** [comment] 2019-03-08 08:59
Do you mean, number of builds pr deploy?

**Comment by henninghaakonsen** [comment] 2019-03-08 09:00
No I mean number of deploys with a unique build. (antall produksjonsettinger)

**Comment by Kyrremann** [comment] 2019-03-08 09:01
Han tenker på den samme featuren som vi har i Naisd, altså at vi lager en annotation per deploy.

**Comment by VegarM** [comment] 2019-03-08 09:02
Relatert til #36

**Comment by ambientsound** [comment] 2019-06-24 09:19
I think this is a duplicate of #36 as Vegar mentioned. Closing this; feel free to re-open if this is not the case.

**Closed** 2019-06-24 09:19 UTC
Labels: duplicate
